const questions = [
    ["A", "I like to receive notes of affirmation from you.", "E", "I like it when you hug me."], 
    ["B", "I like to spend one-on-one time with you.", "D", "I feel loved when you give me practical help."],
    ["C", "I like it when you give me gifts.", "B", "I like taking long walks with you."],
    ["D", "I feel loved when you do things to help me.", "E", "I feel loved when you hug or touch me."], 
    ["E", "I feel loved when you hold me in your arms.", "C", "I feel loved when I receive a gift from you."], 
    ["B", "I like to go places with you.", "E", "I like to hold hands with you."], 
    ["A", "I feel loved when you acknowledge me.", "C", "Visible symbols of love (gifts) are very important to me."],
    ["E", "I like to sit close to you.", "A", "I like it when you tell me that I am attractive."], 
    ["B", "I like to spend time with you.", "C", "I like to receive little gifts from you."], 
    ["D", "I know you love me when you help me.", "A", "Your words of acceptance are important to me."], 
    ["B", "I like to be together when we do things.", "A", "I like the kind words you say to me."],
    ["E", "I feel whole when we hug.", "D", "What you do affects me more than what you say."], 
    ["A", "I value your praise and try to avoid your criticism.", "C", "Several inexpensive gifts mean more to me than one large expensive gift."], 
    ["E", "I feel closer to you when you touch me.", "B", "I feel close when we are talking or doing something together."],
    ["A", "I like you to compliment my achievements.", "D", "I know you love me when you do things for me that you don't enjoy doing."],
    ["E", "I like for you to touch me when you walk by.", "B", "I like when you listen to me sympathetically."], 
    ["C", "I really enjoy receiving gifts from you.", "D", "I feel loved when you help me with my home projects."], 
    ["A", "I like when you compliment my appearance.", "B", "I feel loved when you take the time to understand my feelings."], 
    ["E", "I feel secure when you are touching me.", "D", "Your acts of service make me feel loved."], 
    ["D", "I appreciate the many things you do for me.", "C", "I like receiving gifts that you make."], 
    ["B", "I really enjoy the feeling I get when you give me your undivided attention.", "D", "I really enjoy the feeling I get when you do some act of service for me."],
    ["C", "I feel loved when you celebrate my birthday with a gift.", "A", "I feel loved when you celebrate my birthday with meaningful words (written or spoken.)"], 
    ["D", "I feel loved when you help me out with my chores.", "C", "I know you are thinking of me when you give me a gift."], 
    ["C", "I appreciate it when you remember special days with a gift.", "B", "I appreciate it when you listen patiently and don't interrupt me."], 
    ["B", "I enjoy extended trips with you.", "D", "I like to know that you are concerned enough to help me with my daily task."], 
    ["E", "Kissing me unexpectedly makes me feel loved.", "C", "Giving me a gift for no occasion makes me feel loved."], 
    ["A", "I like to be told that you appreciate me.", "B", "I like for you to look at me when we are talking."], 
    ["C", "Your gifts are always special to me.", "E", "I feel loved when you kiss me."], 
    ["A", "I feel loved when you tell me how much you appreciate me.", "D", "I feel loved when you enthusiastically do a task I have requested."], 
    ["E", "I need to be hugged by you every day.", "A", "I need your words of affirmation daily."] 
];